# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.mlx.automatic_speech_recognition
from nodetool.workflows.base_node import BaseNode


class Whisper(
    GraphNode[nodetool.nodes.mlx.automatic_speech_recognition.Whisper.OutputType]
):
    """

    Transcribe an audio asset using MLX Whisper.
    whisper, mlx, asr, speech-to-text

    - Uses MLX for efficient Apple Silicon acceleration
    - Returns transcript and segments with optional word-level timestamps
    """

    Model: typing.ClassVar[type] = (
        nodetool.nodes.mlx.automatic_speech_recognition.Whisper.Model
    )

    model: nodetool.nodes.mlx.automatic_speech_recognition.Whisper.Model = Field(
        default=nodetool.nodes.mlx.automatic_speech_recognition.Whisper.Model.TINY_EN,
        description="Model to use for transcription",
    )
    audio: types.AudioRef | OutputHandle[types.AudioRef] = connect_field(
        default=types.AudioRef(type="audio", uri="", asset_id=None, data=None),
        description="The input audio to transcribe.",
    )
    compression_ratio_threshold: float | OutputHandle[float] | None = connect_field(
        default=2.4,
        description="Threshold for gzip compression ratio; above this, the result is treated as failed.",
    )
    logprob_threshold: float | OutputHandle[float] | None = connect_field(
        default=-1.0,
        description="Average log probability threshold; below this, the result is treated as failed.",
    )
    no_speech_threshold: float | OutputHandle[float] | None = connect_field(
        default=0.6,
        description="Threshold for no-speech probability; if exceeded and logprob is low, the segment is considered silent.",
    )
    condition_on_previous_text: bool | OutputHandle[bool] = connect_field(
        default=True,
        description="If True, the previous output is used as a prompt for the next window, improving consistency.",
    )
    word_timestamps: bool | OutputHandle[bool] = connect_field(
        default=False,
        description="If True, extracts word-level timestamps using cross-attention and dynamic time warping.",
    )

    @property
    def out(self) -> "WhisperOutputs":
        return WhisperOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.mlx.automatic_speech_recognition.Whisper

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


class WhisperOutputs(OutputsProxy):
    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self["text"])

    @property
    def segments(self) -> OutputHandle[list]:
        return typing.cast(OutputHandle[list], self["segments"])
