# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.mlx.text_generation
from nodetool.workflows.base_node import BaseNode


class TextGeneration(
    GraphNode[nodetool.nodes.mlx.text_generation.TextGeneration.OutputType]
):
    """

    Generate text using locally cached MLX models on Apple Silicon.
    text, generation, mlx, local-llm

    Use cases:
    - Fast local iteration with MLX-converted instruction models
    - Privacy-preserving summarization, drafting, or Q&A
    - Building multi-node agent workflows without external APIs
    """

    model: types.LanguageModel | OutputHandle[types.LanguageModel] = connect_field(
        default=types.LanguageModel(
            type="language_model",
            provider=nodetool.metadata.types.Provider.MLX,
            id="mlx-community/Qwen3.5-0.8B-OptiQ-4bit",
            name="Qwen3.5 0.8B OptiQ (4-bit)",
        ),
        description="MLX language model to use for generation. The model must be available in the local Hugging Face cache.",
    )
    system_prompt: str | OutputHandle[str] = connect_field(
        default="You are a helpful assistant.",
        description="Optional system prompt used to steer the model.",
    )
    prompt: str | OutputHandle[str] = connect_field(
        default="", description="The user prompt used for generation."
    )
    max_new_tokens: int | OutputHandle[int] = connect_field(
        default=256, description="Maximum number of tokens the model should generate."
    )
    temperature: float | OutputHandle[float] = connect_field(
        default=0.7,
        description="Sampling temperature. Set to 0 for deterministic output.",
    )
    top_p: float | OutputHandle[float] = connect_field(
        default=0.95, description="Nucleus sampling probability mass."
    )
    top_k: int | OutputHandle[int] = connect_field(
        default=50, description="Limits sampling to the top K tokens at each step."
    )
    min_p: float | OutputHandle[float] = connect_field(
        default=0.0, description="Minimum token probability threshold (0 disables)."
    )
    min_tokens_to_keep: int | OutputHandle[int] = connect_field(
        default=1,
        description="Ensures at least this many tokens remain after filtering.",
    )

    @property
    def out(self) -> "TextGenerationOutputs":
        return TextGenerationOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.mlx.text_generation.TextGeneration

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


class TextGenerationOutputs(OutputsProxy):
    @property
    def text(self) -> OutputHandle[str]:
        return typing.cast(OutputHandle[str], self["text"])

    @property
    def chunk(self) -> OutputHandle[nodetool.metadata.types.Chunk]:
        return typing.cast(OutputHandle[nodetool.metadata.types.Chunk], self["chunk"])
