# This file is auto-generated by nodetool.dsl.codegen.
# Please do not edit this file manually.

# Instead, edit the node class in the source module and run the following commands to regenerate the DSL:
# nodetool package scan
# nodetool codegen

from pydantic import BaseModel, Field
import typing
from typing import Any
import nodetool.metadata.types
import nodetool.metadata.types as types
from nodetool.dsl.graph import GraphNode, SingleOutputGraphNode

import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.mlx.text_to_speech
from nodetool.workflows.base_node import BaseNode


class KokoroTTS(GraphNode[nodetool.nodes.mlx.text_to_speech.BaseMLXTTS.OutputType]):
    """
    MLX Kokoro text-to-speech.
    """

    Model: typing.ClassVar[type] = nodetool.nodes.mlx.text_to_speech.KokoroTTS.Model
    Voice: typing.ClassVar[type] = nodetool.nodes.mlx.text_to_speech.KokoroTTS.Voice
    LanguageCode: typing.ClassVar[type] = (
        nodetool.nodes.mlx.text_to_speech.KokoroTTS.LanguageCode
    )

    text: str | OutputHandle[str] = connect_field(
        default="Hello from MLX TTS.",
        description="Text content to synthesize into speech.",
    )
    speed: float | OutputHandle[float] = connect_field(
        default=1.0, description="Speech speed multiplier for Kokoro (0.5–2.0)."
    )
    model: nodetool.nodes.mlx.text_to_speech.KokoroTTS.Model = Field(
        default=nodetool.nodes.mlx.text_to_speech.KokoroTTS.Model.KOKORO_82M,
        description="Kokoro model variant to load.",
    )
    voice: nodetool.nodes.mlx.text_to_speech.KokoroTTS.Voice = Field(
        default=nodetool.nodes.mlx.text_to_speech.KokoroTTS.Voice.AF_HEART,
        description="Voice preset supported by Kokoro (e.g. af_heart, am_adam, bf_emma).",
    )
    language: nodetool.nodes.mlx.text_to_speech.KokoroTTS.LanguageCode = Field(
        default=nodetool.nodes.mlx.text_to_speech.KokoroTTS.LanguageCode.AMERICAN_ENGLISH,
        description="Language code",
    )
    temperature: float | OutputHandle[float] = connect_field(
        default=0.7, description="Sampling temperature passed to the Kokoro generator."
    )

    @property
    def out(self) -> "KokoroTTSOutputs":
        return KokoroTTSOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.mlx.text_to_speech.KokoroTTS

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


class KokoroTTSOutputs(OutputsProxy):
    @property
    def audio(self) -> OutputHandle[nodetool.metadata.types.AudioRef]:
        return typing.cast(
            OutputHandle[nodetool.metadata.types.AudioRef], self["audio"]
        )

    @property
    def chunk(self) -> OutputHandle[types.Chunk]:
        return typing.cast(OutputHandle[types.Chunk], self["chunk"])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.mlx.text_to_speech
from nodetool.workflows.base_node import BaseNode


class SesameTTS(GraphNode[nodetool.nodes.mlx.text_to_speech.BaseMLXTTS.OutputType]):
    """
    MLX Sesame / CSM text-to-speech with reference audio cloning.
    """

    Model: typing.ClassVar[type] = nodetool.nodes.mlx.text_to_speech.SesameTTS.Model

    text: str | OutputHandle[str] = connect_field(
        default="Hello from MLX TTS.",
        description="Text content to synthesize into speech.",
    )
    speed: float | OutputHandle[float] = connect_field(
        default=1.0, description="Speech speed multiplier for Sesame (0.5–2.0)."
    )
    model: nodetool.nodes.mlx.text_to_speech.SesameTTS.Model = Field(
        default=nodetool.nodes.mlx.text_to_speech.SesameTTS.Model.SESAME_1B,
        description="Sesame/CSM model variant to load.",
    )
    reference_audio: types.AudioRef | OutputHandle[types.AudioRef] = connect_field(
        default=PydanticUndefined,
        description="Reference audio clip used for voice cloning.",
    )

    @property
    def out(self) -> "SesameTTSOutputs":
        return SesameTTSOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.mlx.text_to_speech.SesameTTS

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


class SesameTTSOutputs(OutputsProxy):
    @property
    def audio(self) -> OutputHandle[nodetool.metadata.types.AudioRef]:
        return typing.cast(
            OutputHandle[nodetool.metadata.types.AudioRef], self["audio"]
        )

    @property
    def chunk(self) -> OutputHandle[types.Chunk]:
        return typing.cast(OutputHandle[types.Chunk], self["chunk"])


import typing
from pydantic import Field
from nodetool.dsl.handles import OutputHandle, OutputsProxy, connect_field
import nodetool.nodes.mlx.text_to_speech
from nodetool.workflows.base_node import BaseNode


class SparkTTS(GraphNode[nodetool.nodes.mlx.text_to_speech.BaseMLXTTS.OutputType]):
    """
    MLX Spark text-to-speech.
    """

    Speed: typing.ClassVar[type] = nodetool.nodes.mlx.text_to_speech.SparkTTS.Speed
    Model: typing.ClassVar[type] = nodetool.nodes.mlx.text_to_speech.SparkTTS.Model
    Pitch: typing.ClassVar[type] = nodetool.nodes.mlx.text_to_speech.SparkTTS.Pitch
    Gender: typing.ClassVar[type] = nodetool.nodes.mlx.text_to_speech.SparkTTS.Gender

    text: str | OutputHandle[str] = connect_field(
        default="Hello from MLX TTS.",
        description="Text content to synthesize into speech.",
    )
    speed: nodetool.nodes.mlx.text_to_speech.SparkTTS.Speed = Field(
        default=nodetool.nodes.mlx.text_to_speech.SparkTTS.Speed.MODERATE,
        description="Spark speed preset (very_low, low, moderate, high, very_high).",
    )
    model: nodetool.nodes.mlx.text_to_speech.SparkTTS.Model = Field(
        default=nodetool.nodes.mlx.text_to_speech.SparkTTS.Model.SPARK_TTS_0_5B_BF16,
        description="Spark model variant to load.",
    )
    voice: str | OutputHandle[str] | None = connect_field(
        default=None, description="Optional Spark voice preset."
    )
    pitch: nodetool.nodes.mlx.text_to_speech.SparkTTS.Pitch = Field(
        default=nodetool.nodes.mlx.text_to_speech.SparkTTS.Pitch.MODERATE,
        description="Spark pitch preset.",
    )
    gender: nodetool.nodes.mlx.text_to_speech.SparkTTS.Gender = Field(
        default=nodetool.nodes.mlx.text_to_speech.SparkTTS.Gender.FEMALE,
        description="Spark voice gender.",
    )

    @property
    def out(self) -> "SparkTTSOutputs":
        return SparkTTSOutputs(self)

    @classmethod
    def get_node_class(cls) -> type[BaseNode]:
        return nodetool.nodes.mlx.text_to_speech.SparkTTS

    @classmethod
    def get_node_type(cls):
        return cls.get_node_class().get_node_type()


class SparkTTSOutputs(OutputsProxy):
    @property
    def audio(self) -> OutputHandle[nodetool.metadata.types.AudioRef]:
        return typing.cast(
            OutputHandle[nodetool.metadata.types.AudioRef], self["audio"]
        )

    @property
    def chunk(self) -> OutputHandle[types.Chunk]:
        return typing.cast(OutputHandle[types.Chunk], self["chunk"])
